### ISSUE TITLE
评论初始化问题

### ISSUE THREAD

**Issue by yinaoxiong** [panjunwen/Valine#10]
中文用户请注意：请尽量用**英文**描述你的 issue，这样能够让尽可能多的人帮到你。

If you want to report a bug, please provide the following information:

- The steps to reproduce.
- A minimal demo of the problem via https://jsfiddle.net or http://codepen.io/pen if possible.
- Which versions of Valine, and which browser / OS are affected by this issue?
版本：1.2.0
问题：第一次使用的时候由于不存在comment这个classes，导致评论列表一直加载中界面卡顿，无法发表第一条评论进行classes的初始化，问题陷入死循环。问题截图如下。
![image](https://user-images.githubusercontent.com/23397945/73610556-aed8fb00-4613-11ea-958a-9182d37c6cbd.png)
![image](https://user-images.githubusercontent.com/23397945/73610560-c44e2500-4613-11ea-83a9-a5b2a7525035.png)

**Comment by beautycss** [comment]
我也遇到这个问题，使用了你发布的 [1.2.1版本](https://github.com/YinAoXiong/Valine/blob/756a2139f2ad27244a576def239377b786eb5dcd/dist/Valine.min.js)可以了。 👍👍
