### ISSUE TITLE
Failed to load resource: the server responded with a status of 404 ()

### ISSUE THREAD

**Issue by so1ve** [panjunwen/Valine#12]
I don't know why my Valine returns `Failed to load resource: the server responded with a status of 404 () `in the console, LeanCloud prompts` {"code": 401, "error": "Unauthorized."}`

**Comment by yinaoxiong** [comment]
> I don't know why my Valine returns `Failed to load resource: the server responded with a status of 404 () `in the console, LeanCloud prompts` {"code": 401, "error": "Unauthorized."}`
 @FFRaycoder  Because there is no comment class in learncloud，and it is same as Issue #10 . Pll requests #11 can fix it.

**Comment by so1ve** [comment]
> > I don't know why my Valine returns `Failed to load resource: the server responded with a status of 404 () `in the console, LeanCloud prompts` {"code": 401, "error": "Unauthorized."}`
> > @FFRaycoder  Because there is no comment class in learncloud，and it is same as Issue #10 . Pll requests #11 can fix it.

Thank you, it works now.
