### ISSUE TITLE
沒頭像和每個人都有“博主”圖標

### ISSUE THREAD

**Issue by jerryc127** [panjunwen/Valine#6]
中文用户请注意：请尽量用**英文**描述你的 issue，这样能够让尽可能多的人帮到你。

If you want to report a bug, please provide the following information:

- The steps to reproduce.
- A minimal demo of the problem via https://jsfiddle.net or http://codepen.io/pen if possible.
- Which versions of Valine, and which browser / OS are affected by this issue?

![image](https://user-images.githubusercontent.com/16351105/66228251-81d21580-e711-11e9-9274-474504a9e71e.png)
![image](https://user-images.githubusercontent.com/16351105/66228316-b219b400-e711-11e9-811b-4aba5234335c.png)

我哪裏配置錯/？

**Comment by jubyshu** [comment]
加个`admin_email`选项
